# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de la aplicación
COPY chivas.py .

# Comando para ejecutar la aplicación
CMD ["python", "./chivas.py"]